language: php

php:
  - 5.4
  - 5.5

env:
  - CODECEPTION_VERSION="2.*"

before_script:
  - composer self-update
  - composer install -n --prefer-dist --dev
  - composer require codeception/codeception:${CODECEPTION_VERSION}

script: "php -dxdebug.remote_enable=1 vendor/codeception/codeception/codecept run --debug"